### ISSUE TITLE
文档示例地址咋访问不了了呀

### ISSUE THREAD

**Issue by enjoyWeb** [qq20004604/wti-form#5]
文档示例地址咋访问不了了呀

**Comment by qq20004604** [comment]
应该可以的吧，我刚试了一下没问题。
也可以考虑 fork 项目：wti-form-demo，该项目是文档的源代码

**Comment by enjoyWeb** [comment]
╭(╯3╰)╮亲！你的信件我已经收到了，我会尽快查看的O(∩_∩)O哈！
